# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-19 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawadi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='../static/images/defaul.jpg', upload_to='media/'),
        ),
    ]
