# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-19 09:49
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zawadi', '0002_auto_20210719_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
